#!/bin/sh

if ! cargo fmt -- --check ; then
    cat <<\EOF

There are some code style issues, run `cargo fmt` first.
EOF
    exit 1
fi

if ! cargo clippy 2> /dev/null; then
	cat <<\EOF

Fix clippy errors
EOF
	exit 1
fi
